---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-guacamole
  namespace: guacamole
spec:
  secretName: certificate-guacamole
  commonName: cbxon.co.uk
  subject:
    organizations:
      - cbxon
  dnsNames:
    - cbxon.co.uk
    - guacamole.cbxon.co.uk
  issuerRef:
    kind: ClusterIssuer
    name: cert-cluster-issuer
