apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- secret.yaml
- persistentVolume.yaml
- persistentVolumeClaim.yaml
- service.yaml
- deployment.yaml
- certificate.yaml
- ingress.yaml