---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacamole-pv-claim
  namespace: guacamole
  labels:
    app: guacamole
spec:
  volumeName: guacamole-pv
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany