---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wireguard-pv
  namespace: wireguard
  labels:
    app: wireguard
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /cluster/config/wireguard