---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wireguard
  name: service-wireguard
  namespace: wireguard
spec:
  ports:
  - port: 51820
    protocol: UDP
    targetPort: wg-server-port
  selector:
    app: wireguard
  type: LoadBalancer