apiVersion: v1
kind: Service
metadata:
  labels:
    app: wireguard
  name: service-wireguard
  namespace: default
spec:
  clusterIP: 10.43.227.199
  ports:
  - port: 51820
    protocol: UDP
    targetPort: wg-server-port
  selector:
    app: wireguard
  type: LoadBalancer