---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-kube-prometheus-stack
  namespace: kube-prometheus-stack
spec:
  secretName: certificate-kube-prometheus-stack
  dnsNames:
    - grafana.cbxon.co.uk
  issuerRef:
    kind: ClusterIssuer
    name: cert-cluster-issuer
