---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "71.2.0"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: default
      interval: 10m
      createNamespace: true
      targetNamespace: kube-prometheus-stack
  values:
    prometheus:
      prometheusSpec:
        additionalScrapeConfigs:
          - job_name: 'node-exporter'
            static_configs:
              - targets: ['192.168.20.20:9100']
                labels:
                  instance: 'storage-server'
