apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-mediastack
  namespace: default
spec:
  secretName: certificate-mediastack
  dnsNames:
    - jellyseerr.cbxon.co.uk
    - radarr.cbxon.co.uk
    - sonarr.cbxon.co.uk
    - jellyfin.cbxon.co.uk
    - prowlarr.cbxon.co.uk
    - qbittorrent.cbxon.co.uk
  commonName: cbxon.co.uk
  issuerRef:
    kind: ClusterIssuer
    name: cert-cluster-issuer
