---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbit-pv
  namespace: default
  labels:
    app: mediastack
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /cluster/config/qbit
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbit-pv-claim
  namespace: default
  labels:
    app: mediastack
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mediastack
  name: downloader-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediastack
  template:
    metadata:
      labels:
        app: mediastack
    spec:
      volumes:
        - name: qbit-config
          persistentVolumeClaim:
            claimName: qbit-pv-claim
        - name: downloads
          nfs:
            server: 192.168.20.20
            path: /mnt/nfs/data/downloads
      initContainers:
        - name: gluetun
          image: qmcgaw/gluetun:latest
          restartPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          envFrom:
            - secretRef:
                name: gluetun-conf
      containers:
      - name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent:latest
        ports:
          - containerPort: 8080
            name: qbit-http
        env:
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: "Etc/UTC"
          - name: WEBUI_PORT
            value: "8080"
        volumeMounts:
          - mountPath: "/config"
            name: qbit-config
          - mountPath: "/downloads"
            name: downloads
      dnsPolicy: ClusterFirst
      restartPolicy: Always